<a href="https://colab.research.google.com/github/GabrielSorge/analise-aproveitamento-fora-times-brasileirao/blob/main/Visita_maior_aproveitamento.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [81]:
import pandas as pd

df = pd.read_csv("matches-2003-2025.txt", sep = ";", encoding = "latin1")

df.shape

(9166, 5)

In [82]:

df.head()

        #DATE   HOUR       HOME-TEAM SCORE    AWAY-TEAM
0  29/03/2003  18:00      Guarani/SP   4x2     Vasco/RJ
1  29/03/2003  18:00     Atlético/PR   2x0    Grêmio/RS
2  30/03/2003  18:00        Goiás/GO   2x2  Paysandu/PA
3  30/03/2003  18:00  Corinthians/SP   0x3  Atlético/MG
4  30/03/2003  16:00     Flamengo/RJ   1x1  Coritiba/PR

In [83]:
df.dtypes

#DATE        object
HOUR         object
HOME-TEAM    object
SCORE        object
AWAY-TEAM    object
dtype: object

In [84]:
df["#DATE"].head()

0    29/03/2003
1    29/03/2003
2    30/03/2003
3    30/03/2003
4    30/03/2003
Name: #DATE, dtype: object

In [85]:
df["#DATE"] = pd.to_datetime(df["#DATE"])
df["#DATE"]

/tmp/ipykernel_8091/3919501472.py:1: UserWarning: Parsing dates in %d/%m/%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df["#DATE"] = pd.to_datetime(df["#DATE"])

0      2003-03-29
1      2003-03-29
2      2003-03-30
3      2003-03-30
4      2003-03-30
          ...
9161   2025-12-07
9162   2025-12-07
9163   2025-12-07
9164   2025-12-07
9165   2025-12-07
Name: #DATE, Length: 9166, dtype: datetime64[ns]

In [86]:

def verifica_resultado(score):
  placar = score.split("x")

  casa = int(placar[0])
  visitante = int(placar[1])

  if casa > visitante:
    resultado_visitante = "derrota"
  elif casa == visitante:
    resultado_visitante = "empate"
  else:
    resultado_visitante = "vitoria"

  return resultado_visitante

In [87]:
df["RESULTADO_VISITANTE"] = df["SCORE"].apply(verifica_resultado)
df[["RESULTADO_VISITANTE", "AWAY-TEAM"]]

     RESULTADO_VISITANTE      AWAY-TEAM
0                derrota       Vasco/RJ
1                derrota      Grêmio/RS
2                 empate    Paysandu/PA
3                vitoria    Atlético/MG
4                 empate    Coritiba/PR
...                  ...            ...
9161             derrota       Bahia/BA
9162             derrota  Bragantino/SP
9163             derrota    Cruzeiro/MG
9164             vitoria      Grêmio/RS
9165             derrota   São Paulo/SP

[9166 rows x 2 columns]

In [88]:
jogos_fora = df.groupby("AWAY-TEAM")["AWAY-TEAM"].count()
print(jogos_fora)

AWAY-TEAM
América/MG            114
América/RN             19
Atlético/GO           152
Atlético/MG           428
Atlético/PR           409
Avaí/SC               133
Bahia/BA              251
Barueri/SP             19
Botafogo/RJ           386
Bragantino/SP         114
Brasiliense/DF         21
CSA/AL                 19
Ceará/CE              152
Chapecoense/SC        133
Corinthians/SP        428
Coritiba/PR           295
Criciúma/SC           103
Cruzeiro/MG           390
Cuiabá/MT              76
Figueirense/SC        219
Flamengo/RJ           447
Fluminense/RJ         447
Fortaleza/CE          196
Goiás/GO              295
Grêmio Prudente/SP     19
Grêmio/RS             407
Guarani/SP             65
Internacional/RS      428
Ipatinga/MG            19
Joinville/SC           19
Juventude/RS          181
Mirassol/SP            19
Náutico/PE             95
Palmeiras/SP          405
Paraná/PR             124
Paysandu/PA            67
Ponte Preta/SP        181
Portuguesa/SP          57
Santa Cruz/PE          38
Santo André/SP         19
Santos/SP             428
Sport/PE              228
São Caetano/SP         86
São Paulo/SP          447
Vasco/RJ              352
Vitória/BA            236
Name: AWAY-TEAM, dtype: int64

In [89]:
def pontos_partida(resultado):
  if resultado == "derrota":
    return 0
  elif resultado == "empate":
    return 1
  elif resultado == "vitoria":
    return 3

In [90]:
df["PONTOS"] = df["RESULTADO_VISITANTE"].apply(pontos_partida)

In [95]:
pontos = df.groupby("AWAY-TEAM")["PONTOS"].sum()
print(pontos)

AWAY-TEAM
América/MG             71
América/RN              8
Atlético/GO           135
Atlético/MG           476
Atlético/PR           368
Avaí/SC                94
Bahia/BA              206
Barueri/SP             12
Botafogo/RJ           416
Bragantino/SP         113
Brasiliense/DF         17
CSA/AL                  9
Ceará/CE              121
Chapecoense/SC        106
Corinthians/SP        500
Coritiba/PR           225
Criciúma/SC            65
Cruzeiro/MG           470
Cuiabá/MT              78
Figueirense/SC        196
Flamengo/RJ           570
Fluminense/RJ         488
Fortaleza/CE          180
Goiás/GO              271
Grêmio Prudente/SP     11
Grêmio/RS             427
Guarani/SP             35
Internacional/RS      480
Ipatinga/MG             5
Joinville/SC            6
Juventude/RS          127
Mirassol/SP            24
Náutico/PE             55
Palmeiras/SP          532
Paraná/PR              97
Paysandu/PA            33
Ponte Preta/SP        144
Portuguesa/SP          36
Santa Cruz/PE          14
Santo André/SP         12
Santos/SP             458
Sport/PE              158
São Caetano/SP         87
São Paulo/SP          548
Vasco/RJ              336
Vitória/BA            186
Name: PONTOS, dtype: int64

In [97]:
pontos_possiveis = jogos_fora * 3
print(pontos_possiveis)

AWAY-TEAM
América/MG             342
América/RN              57
Atlético/GO            456
Atlético/MG           1284
Atlético/PR           1227
Avaí/SC                399
Bahia/BA               753
Barueri/SP              57
Botafogo/RJ           1158
Bragantino/SP          342
Brasiliense/DF          63
CSA/AL                  57
Ceará/CE               456
Chapecoense/SC         399
Corinthians/SP        1284
Coritiba/PR            885
Criciúma/SC            309
Cruzeiro/MG           1170
Cuiabá/MT              228
Figueirense/SC         657
Flamengo/RJ           1341
Fluminense/RJ         1341
Fortaleza/CE           588
Goiás/GO               885
Grêmio Prudente/SP      57
Grêmio/RS             1221
Guarani/SP             195
Internacional/RS      1284
Ipatinga/MG             57
Joinville/SC            57
Juventude/RS           543
Mirassol/SP             57
Náutico/PE             285
Palmeiras/SP          1215
Paraná/PR              372
Paysandu/PA            201
Ponte Preta/SP         543
Portuguesa/SP          171
Santa Cruz/PE          114
Santo André/SP          57
Santos/SP             1284
Sport/PE               684
São Caetano/SP         258
São Paulo/SP          1341
Vasco/RJ              1056
Vitória/BA             708
Name: AWAY-TEAM, dtype: int64

In [107]:
aproveitamento = (pontos / pontos_possiveis) * 100
print(round(aproveitamento,2).sort_values(ascending=False))

AWAY-TEAM
Palmeiras/SP          43.79
Flamengo/RJ           42.51
Mirassol/SP           42.11
São Paulo/SP          40.87
Cruzeiro/MG           40.17
Corinthians/SP        38.94
Internacional/RS      37.38
Atlético/MG           37.07
Fluminense/RJ         36.39
Botafogo/RJ           35.92
Santos/SP             35.67
Grêmio/RS             34.97
Cuiabá/MT             34.21
São Caetano/SP        33.72
Bragantino/SP         33.04
Vasco/RJ              31.82
Goiás/GO              30.62
Fortaleza/CE          30.61
Atlético/PR           29.99
Figueirense/SC        29.83
Atlético/GO           29.61
Bahia/BA              27.36
Brasiliense/DF        26.98
Chapecoense/SC        26.57
Ceará/CE              26.54
Ponte Preta/SP        26.52
Vitória/BA            26.27
Paraná/PR             26.08
Coritiba/PR           25.42
Avaí/SC               23.56
Juventude/RS          23.39
Sport/PE              23.10
Santo André/SP        21.05
Barueri/SP            21.05
Portuguesa/SP         21.05
Criciúma/SC           21.04
América/MG            20.76
Náutico/PE            19.30
Grêmio Prudente/SP    19.30
Guarani/SP            17.95
Paysandu/PA           16.42
CSA/AL                15.79
América/RN            14.04
Santa Cruz/PE         12.28
Joinville/SC          10.53
Ipatinga/MG            8.77
dtype: float64

In [127]:
jogos_fora_sem_outliers = jogos_fora[jogos_fora > 100]
pontos_possiveis_sem_outliers = jogos_fora_sem_outliers * 3
aproveitamento_sem_outliers = (pontos / pontos_possiveis_sem_outliers) * 100

aproveitamento_sem_outliers.dropna().sort_values(ascending=False).round(2)

AWAY-TEAM
Palmeiras/SP        43.79
Flamengo/RJ         42.51
São Paulo/SP        40.87
Cruzeiro/MG         40.17
Corinthians/SP      38.94
Internacional/RS    37.38
Atlético/MG         37.07
Fluminense/RJ       36.39
Botafogo/RJ         35.92
Santos/SP           35.67
Grêmio/RS           34.97
Bragantino/SP       33.04
Vasco/RJ            31.82
Goiás/GO            30.62
Fortaleza/CE        30.61
Atlético/PR         29.99
Figueirense/SC      29.83
Atlético/GO         29.61
Bahia/BA            27.36
Chapecoense/SC      26.57
Ceará/CE            26.54
Ponte Preta/SP      26.52
Vitória/BA          26.27
Paraná/PR           26.08
Coritiba/PR         25.42
Avaí/SC             23.56
Juventude/RS        23.39
Sport/PE            23.10
Criciúma/SC         21.04
América/MG          20.76
dtype: float64